version: '3'

networks:
  ITutor:
    driver: bridge

services:
  postgres:
    env_file: ./docker-env.env
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ITutor

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ITutor

volumes:
  pgdata:
    external: true
